# Generated by Django 6.0.2 on 2026-02-06 19:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email unique pour la connexion",
                        max_length=255,
                        unique=True,
                        verbose_name="Adresse email",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        help_text="Nom et prénom de l'utilisateur",
                        max_length=100,
                        verbose_name="Nom complet",
                    ),
                ),
                (
                    "is_desert_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher si l'utilisateur est un administrateur gouvernemental",
                        verbose_name="Administrateur DesertMet",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'inscription",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID unique",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom unique identifiant la station",
                        max_length=100,
                        unique=True,
                        verbose_name="Nom de la station",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Coordonnée GPS : -90 à +90",
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Coordonnée GPS : -180 à +180",
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "energie",
                    models.CharField(
                        choices=[
                            ("SOLAIRE", "Solaire"),
                            ("BATTERIE", "Batterie"),
                            ("HYBRIDE", "Hybride (Solaire + Batterie)"),
                        ],
                        default="SOLAIRE",
                        help_text="Type de source d'énergie",
                        max_length=20,
                        verbose_name="Source d'énergie",
                    ),
                ),
                (
                    "communication",
                    models.CharField(
                        choices=[
                            ("SATELLITE", "Satellite"),
                            ("GSM", "Réseau GSM"),
                            ("LORA", "LoRa"),
                        ],
                        default="SATELLITE",
                        help_text="Méthode de transmission des données",
                        max_length=20,
                        verbose_name="Type de communication",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("MAINTENANCE", "En maintenance"),
                            ("EN_PANNE", "En panne"),
                        ],
                        default="ACTIF",
                        help_text="État actuel de fonctionnement",
                        max_length=20,
                        verbose_name="État de la station",
                    ),
                ),
                (
                    "capteur_temperature",
                    models.BooleanField(
                        default=True,
                        help_text="La station possède-t-elle un capteur de température ?",
                        verbose_name="Capteur de température",
                    ),
                ),
                (
                    "capteur_pression",
                    models.BooleanField(
                        default=True,
                        help_text="La station possède-t-elle un capteur de pression ?",
                        verbose_name="Capteur de pression",
                    ),
                ),
                (
                    "capteur_vent",
                    models.BooleanField(
                        default=True,
                        help_text="La station possède-t-elle un capteur de vent ?",
                        verbose_name="Capteur de vent",
                    ),
                ),
                (
                    "capteur_ensoleillement",
                    models.BooleanField(
                        default=True,
                        help_text="La station possède-t-elle un capteur d'ensoleillement ?",
                        verbose_name="Capteur d'ensoleillement",
                    ),
                ),
                (
                    "capteur_precipitation",
                    models.BooleanField(
                        default=True,
                        help_text="La station possède-t-elle un capteur de précipitation ?",
                        verbose_name="Capteur de précipitation",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_mise_a_jour",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Station météorologique",
                "verbose_name_plural": "Stations météorologiques",
                "ordering": ["nom"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="users_stati_status_5a997a_idx"
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="users_stati_latitud_1d83be_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE_STATION", "Création de station"),
                            ("UPDATE_STATION", "Modification de station"),
                            ("DELETE_STATION", "Suppression de station"),
                            ("CHANGE_STATUS", "Changement de statut"),
                            ("UPDATE_PARAMETERS", "Modification de paramètres"),
                            ("USER_MANAGEMENT", "Gestion utilisateur"),
                            ("SYSTEM_ACTION", "Action système"),
                        ],
                        help_text="Catégorie de l'action effectuée",
                        max_length=50,
                        verbose_name="Type d'action",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description détaillée de l'action effectuée",
                        verbose_name="Description",
                    ),
                ),
                (
                    "donnees_avant",
                    models.JSONField(
                        blank=True,
                        help_text="État des données avant l'action (format JSON)",
                        null=True,
                        verbose_name="Données avant modification",
                    ),
                ),
                (
                    "donnees_apres",
                    models.JSONField(
                        blank=True,
                        help_text="État des données après l'action (format JSON)",
                        null=True,
                        verbose_name="Données après modification",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Moment exact de l'action",
                        verbose_name="Date et heure",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Adresse IP de l'administrateur au moment de l'action",
                        null=True,
                        verbose_name="Adresse IP",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Administrateur ayant effectué l'action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_admin",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Administrateur",
                    ),
                ),
                (
                    "utilisateur_concerne",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur affecté par cette action (si applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_utilisateur",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur concerné",
                    ),
                ),
                (
                    "station_concerne",
                    models.ForeignKey(
                        blank=True,
                        help_text="Station affectée par cette action (si applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_station",
                        to="users.station",
                        verbose_name="Station concernée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log administrateur",
                "verbose_name_plural": "Logs administrateurs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["admin", "timestamp"],
                        name="users_admin_admin_i_cce586_idx",
                    ),
                    models.Index(
                        fields=["action_type"], name="users_admin_action__349571_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Température en degrés Celsius",
                        max_digits=5,
                        null=True,
                        verbose_name="Température (°C)",
                    ),
                ),
                (
                    "pression",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pression en hectopascals",
                        max_digits=6,
                        null=True,
                        verbose_name="Pression atmosphérique (hPa)",
                    ),
                ),
                (
                    "vitesse_vent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vitesse du vent en kilomètres par heure",
                        max_digits=6,
                        null=True,
                        verbose_name="Vitesse du vent (km/h)",
                    ),
                ),
                (
                    "precipitation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quantité de pluie en millimètres",
                        max_digits=6,
                        null=True,
                        verbose_name="Précipitations (mm)",
                    ),
                ),
                (
                    "ensoleillement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rayonnement solaire en watts par mètre carré",
                        max_digits=6,
                        null=True,
                        verbose_name="Ensoleillement (W/m²)",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Moment exact où les données ont été collectées",
                        verbose_name="Date et heure du relevé",
                    ),
                ),
                (
                    "date_reception",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date à laquelle le système a reçu ces données",
                        verbose_name="Date de réception",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        help_text="Station qui a généré ces données",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donnees_meteo",
                        to="users.station",
                        verbose_name="Station émettrice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donnée météorologique",
                "verbose_name_plural": "Données météorologiques",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["station", "timestamp"],
                        name="users_weath_station_26e0f6_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="users_weath_timesta_991d0e_idx"
                    ),
                ],
            },
        ),
    ]
