--
-- PostgreSQL database dump
--

\restrict DbomEvbIBEXvAW50biw3SkaG8O3Ok0X92UGcy3Uj9VpNNcww8TiLlP6qDnthqXf

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-02-08 14:01:56

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 16431)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: desertmet_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO desertmet_user;

--
-- TOC entry 225 (class 1259 OID 16430)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: desertmet_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16441)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: desertmet_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO desertmet_user;

--
-- TOC entry 227 (class 1259 OID 16440)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: desertmet_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16421)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: desertmet_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO desertmet_user;

--
-- TOC entry 223 (class 1259 OID 16420)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: desertmet_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 16619)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: desertmet_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO desertmet_user;

--
-- TOC entry 239 (class 1259 OID 16618)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: desertmet_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16409)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: desertmet_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO desertmet_user;

--
-- TOC entry 221 (class 1259 OID 16408)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: desertmet_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16397)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: desertmet_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO desertmet_user;

--
-- TOC entry 219 (class 1259 OID 16396)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: desertmet_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16645)
-- Name: django_session; Type: TABLE; Schema: public; Owner: desertmet_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO desertmet_user;

--
-- TOC entry 236 (class 1259 OID 16537)
-- Name: users_adminlog; Type: TABLE; Schema: public; Owner: desertmet_user
--

CREATE TABLE public.users_adminlog (
    id uuid NOT NULL,
    action_type character varying(50) NOT NULL,
    description text NOT NULL,
    donnees_avant jsonb,
    donnees_apres jsonb,
    "timestamp" timestamp with time zone NOT NULL,
    ip_address inet,
    admin_id bigint,
    utilisateur_concerne_id bigint,
    station_concerne_id uuid
);


ALTER TABLE public.users_adminlog OWNER TO desertmet_user;

--
-- TOC entry 235 (class 1259 OID 16516)
-- Name: users_station; Type: TABLE; Schema: public; Owner: desertmet_user
--

CREATE TABLE public.users_station (
    id uuid NOT NULL,
    nom character varying(100) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL,
    energie character varying(20) NOT NULL,
    communication character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    capteur_temperature boolean NOT NULL,
    capteur_pression boolean NOT NULL,
    capteur_vent boolean NOT NULL,
    capteur_ensoleillement boolean NOT NULL,
    capteur_precipitation boolean NOT NULL,
    date_creation timestamp with time zone NOT NULL,
    date_mise_a_jour timestamp with time zone NOT NULL
);


ALTER TABLE public.users_station OWNER TO desertmet_user;

--
-- TOC entry 230 (class 1259 OID 16478)
-- Name: users_user; Type: TABLE; Schema: public; Owner: desertmet_user
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    email character varying(255) NOT NULL,
    fullname character varying(100) NOT NULL,
    is_desert_admin boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.users_user OWNER TO desertmet_user;

--
-- TOC entry 232 (class 1259 OID 16499)
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: desertmet_user
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO desertmet_user;

--
-- TOC entry 231 (class 1259 OID 16498)
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: desertmet_user
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16477)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: desertmet_user
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16508)
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: desertmet_user
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO desertmet_user;

--
-- TOC entry 233 (class 1259 OID 16507)
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: desertmet_user
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16549)
-- Name: users_weatherdata; Type: TABLE; Schema: public; Owner: desertmet_user
--

CREATE TABLE public.users_weatherdata (
    id bigint NOT NULL,
    temperature numeric(5,2),
    pression numeric(6,2),
    vitesse_vent numeric(6,2),
    precipitation numeric(6,2),
    ensoleillement numeric(6,2),
    "timestamp" timestamp with time zone NOT NULL,
    date_reception timestamp with time zone NOT NULL,
    station_id uuid NOT NULL
);


ALTER TABLE public.users_weatherdata OWNER TO desertmet_user;

--
-- TOC entry 237 (class 1259 OID 16548)
-- Name: users_weatherdata_id_seq; Type: SEQUENCE; Schema: public; Owner: desertmet_user
--

ALTER TABLE public.users_weatherdata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_weatherdata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5046 (class 0 OID 16431)
-- Dependencies: 226
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: desertmet_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5048 (class 0 OID 16441)
-- Dependencies: 228
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: desertmet_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5044 (class 0 OID 16421)
-- Dependencies: 224
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: desertmet_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Utilisateur	8	add_user
22	Can change Utilisateur	8	change_user
23	Can delete Utilisateur	8	delete_user
24	Can view Utilisateur	8	view_user
25	Can add Station météorologique	7	add_station
26	Can change Station météorologique	7	change_station
27	Can delete Station météorologique	7	delete_station
28	Can view Station météorologique	7	view_station
29	Can add Log administrateur	6	add_adminlog
30	Can change Log administrateur	6	change_adminlog
31	Can delete Log administrateur	6	delete_adminlog
32	Can view Log administrateur	6	view_adminlog
33	Can add Donnée météorologique	9	add_weatherdata
34	Can change Donnée météorologique	9	change_weatherdata
35	Can delete Donnée météorologique	9	delete_weatherdata
36	Can view Donnée météorologique	9	view_weatherdata
\.


--
-- TOC entry 5060 (class 0 OID 16619)
-- Dependencies: 240
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: desertmet_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 5042 (class 0 OID 16409)
-- Dependencies: 222
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: desertmet_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	users	adminlog
7	users	station
8	users	user
9	users	weatherdata
\.


--
-- TOC entry 5040 (class 0 OID 16397)
-- Dependencies: 220
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: desertmet_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-02-06 20:34:05.029362+01
2	contenttypes	0002_remove_content_type_name	2026-02-06 20:34:05.119881+01
3	auth	0001_initial	2026-02-06 20:34:05.30601+01
4	auth	0002_alter_permission_name_max_length	2026-02-06 20:34:05.312338+01
5	auth	0003_alter_user_email_max_length	2026-02-06 20:34:05.319806+01
6	auth	0004_alter_user_username_opts	2026-02-06 20:34:05.32671+01
7	auth	0005_alter_user_last_login_null	2026-02-06 20:34:05.333261+01
8	auth	0006_require_contenttypes_0002	2026-02-06 20:34:05.335085+01
9	auth	0007_alter_validators_add_error_messages	2026-02-06 20:34:05.341712+01
10	auth	0008_alter_user_username_max_length	2026-02-06 20:34:05.349271+01
11	auth	0009_alter_user_last_name_max_length	2026-02-06 20:34:05.35577+01
12	auth	0010_alter_group_name_max_length	2026-02-06 20:34:05.459962+01
13	auth	0011_update_proxy_permissions	2026-02-06 20:34:05.480301+01
14	auth	0012_alter_user_first_name_max_length	2026-02-06 20:34:05.492063+01
15	users	0001_initial	2026-02-06 20:34:05.752325+01
16	admin	0001_initial	2026-02-06 20:34:05.840374+01
17	admin	0002_logentry_remove_auto_add	2026-02-06 20:34:05.849543+01
18	admin	0003_logentry_add_action_flag_choices	2026-02-06 20:34:05.858605+01
19	sessions	0001_initial	2026-02-06 20:34:05.884714+01
\.


--
-- TOC entry 5061 (class 0 OID 16645)
-- Dependencies: 241
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: desertmet_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
rh7810iqo03yt6iukc69r7xdeoxx2nn2	.eJxVjMsOwiAQRf-FtSG8pLRL934DmYGpRQ0YaBON8d8NSRe6vefc82YetnXxW6PqU2QTk-zwuyGEG-UO4hXypfBQ8loT8q7wnTZ-LpHup939CyzQlv4GiRGFQwQJGqUwGmc9ahIjorP2qJ0icEFhID1LcGTdYCmCMcoaZXu0UWupZE_PR6ovNslBOSE-X_USQIs:1vof63:z1Hn-wQ8OC4ExLucwXCteHhvNNuhl6B6irdEwFpp2Pk	2026-02-09 10:59:23.857672+01
mk0tmxcdpddvnpfdw846x8tqerm99gp0	e30:1vof7U:Xhf44SMRPzNZSvk4248w-UGCNOJX5crmOrQdezz455c	2026-02-09 11:00:52.561416+01
8yv6027dstsw6esf3pc3r775vlaowhag	.eJxVjMsOwiAQRf-FtSG8pLRL934DmYGpRQ0YaBON8d8NSRe6vefc82YetnXxW6PqU2QT0-zwuyGEG-UO4hXypfBQ8loT8q7wnTZ-LpHup939CyzQlv4GiRGFQwQJGqUwGmc9ahIjorP2qJ0icEFhID1LcGTdYCmCMcoaZXu0UWupZE_PR6ovNslBOSE-X_Z2QI0:1voURY:yV12V6HLRcmGJqlh_3pDeKiIr2qFNora6MwHEYd68vQ	2026-02-08 23:36:52.40837+01
vsekpff9loywfvrgfskm58fo92pbpv5g	.eJxVjMsOwiAQRf-FtSG8pLRL934DmYGpRQ0YaBON8d8NSRe6vefc82YetnXxW6PqU2QT0-zwuyGEG-UO4hXypfBQ8loT8q7wnTZ-LpHup939CyzQlv4GiRGFQwQJGqUwGmc9ahIjorP2qJ0icEFhID1LcGTdYCmCMcoaZXu0UWupZE_PR6ovNslBOSE-X_Z2QI0:1voUXc:Nsm2odmOBO2MGfF9PQ6sQEDyCcsnBsHwbHLxoBvFG50	2026-02-08 23:43:08.448282+01
kxgzt0efp0zkjvzxa167flv10u92a89d	.eJxVjMsOwiAQRf-FtSG8pLRL934DmYGpRQ0YaBON8d8NSRe6vefc82YetnXxW6PqU2QT0-zwuyGEG-UO4hXypfBQ8loT8q7wnTZ-LpHup939CyzQlv4GiRGFQwQJGqUwGmc9ahIjorP2qJ0icEFhID1LcGTdYCmCMcoaZXu0UWupZE_PR6ovNslBOSE-X_Z2QI0:1voUfG:Q9Uj7XB0DhsEH_UjhW9cCnDRLOWT4zM0gYHPKTa1gSY	2026-02-08 23:51:02.555382+01
yao8rki3g7kghfvb278lfqtp1w941wep	.eJxVjMsOwiAQRf-FtSG8pLRL934DmYGpRQ0YaBON8d8NSRe6vefc82YetnXxW6PqU2QTk-zwuyGEG-UO4hXypfBQ8loT8q7wnTZ-LpHup939CyzQlv4GiRGFQwQJGqUwGmc9ahIjorP2qJ0icEFhID1LcGTdYCmCMcoaZXu0UWupZE_PR6ovNslBOSE-X_USQIs:1voj2v:0lBgPEi64Zkbh3SanRYqZzOsYlfWH_UbYbXe03tP2dk	2026-02-09 15:12:25.171329+01
qcof9k4422c08238xmz01tgzcy1gs4zy	.eJxVjMsOwiAQRf-FtSG8pLRL934DmYGpRQ0YaBON8d8NSRe6vefc82YetnXxW6PqU2QT0-zwuyGEG-UO4hXypfBQ8loT8q7wnTZ-LpHup939CyzQlv4GiRGFQwQJGqUwGmc9ahIjorP2qJ0icEFhID1LcGTdYCmCMcoaZXu0UWupZE_PR6ovNslBOSE-X_Z2QI0:1voUku:rcn_6CLH_50HPewtqbXWu5jvaxI_26yVqszt-NBHuVg	2026-02-08 23:56:52.058124+01
a27s613xsxk6u3iwcl6z6xue52w15wuw	.eJxVjMsOwiAQRf-FtSG8pLRL934DmYGpRQ0YaBON8d8NSRe6vefc82YetnXxW6PqU2QTk-zwuyGEG-UO4hXypfBQ8loT8q7wnTZ-LpHup939CyzQlv4GiRGFQwQJGqUwGmc9ahIjorP2qJ0icEFhID1LcGTdYCmCMcoaZXu0UWupZE_PR6ovNslBOSE-X_USQIs:1vp2Xm:-VVMI5MyU0kAHWdlUcBkavgXojs_09TiUHd95h0PM8k	2026-02-10 12:01:34.236857+01
rr2jixj0ps080rluj9glqf7opa65e282	.eJxVjDsOwjAQBe_iGln-sWwo6XMGa9fe4ABypDipEHdHllJA-2bmvVWkfStxb7LGOaursur0uzGlp9QO8oPqfdFpqds6s-6KPmjT45LldTvcv4NCrfSaLGc2yEyWPFsTPE9-8GIGZgQ4e3RCmBwn8ZMlFMALSKYQHAQH6vMFBXU4TA:1voUs3:ZrwIoVzsnjhOs7XymqGI_SEFJILsx5gHJfskGKpzAzk	2026-02-09 00:04:15.181857+01
\.


--
-- TOC entry 5056 (class 0 OID 16537)
-- Dependencies: 236
-- Data for Name: users_adminlog; Type: TABLE DATA; Schema: public; Owner: desertmet_user
--

COPY public.users_adminlog (id, action_type, description, donnees_avant, donnees_apres, "timestamp", ip_address, admin_id, utilisateur_concerne_id, station_concerne_id) FROM stdin;
e13091ea-6a82-4240-986f-6ccfffd13dd7	SYSTEM_ACTION	Export des données météorologiques (0 relevés)	\N	\N	2026-02-07 13:41:37.507018+01	127.0.0.1	1	\N	\N
06d2418e-b4bd-4281-9653-90500dda3317	SYSTEM_ACTION	Export des données météorologiques (0 relevés)	\N	\N	2026-02-07 13:42:15.292607+01	127.0.0.1	1	\N	\N
99555964-89b5-4ef1-b89f-bbba8581663e	CREATE_STATION	Création de la station station sahara nord	\N	\N	2026-02-07 12:52:17.519903+01	127.0.0.1	1	\N	\N
673f68db-8eb9-4da4-b559-71c4719b7182	UPDATE_STATION	Modification de la station station sahara sud	{"nom": "station sahara nord", "status": "ACTIF", "energie": "HYBRIDE", "capteurs": ["Température", "Pression", "Vent", "Ensoleillement", "Précipitation"], "latitude": 24.564553, "longitude": 13.568783, "communication": "SATELLITE"}	{"nom": "station sahara sud", "status": "ACTIF", "energie": "HYBRIDE", "capteurs": ["Température", "Pression", "Vent", "Ensoleillement"], "latitude": 24.564553, "longitude": 13.568783, "communication": "SATELLITE"}	2026-02-07 13:43:49.020183+01	127.0.0.1	1	\N	\N
d774801f-7692-4bbb-b40e-505351e986e8	DELETE_STATION	Suppression de la station station sahara sud (0 relevés supprimés)	{"nom": "station sahara sud", "status": "ACTIF", "energie": "HYBRIDE", "capteurs": ["Température", "Pression", "Vent", "Ensoleillement"], "latitude": 24.564553, "longitude": 13.568783, "nb_donnees": 0, "communication": "SATELLITE"}	\N	2026-02-07 13:44:04.19513+01	127.0.0.1	1	\N	\N
dbe85701-8d57-4cbd-b219-69032c01f32d	CREATE_STATION	Création de la station station sahara sud	\N	\N	2026-02-07 13:44:19.661353+01	127.0.0.1	1	\N	da138147-fa03-4867-b261-5c0f82707801
f273029c-21e3-4133-9657-0d2c675c5147	UPDATE_STATION	Modification de la station station sahara sud	{"nom": "station sahara sud", "status": "EN_PANNE", "energie": "SOLAIRE", "capteurs": ["Température", "Pression", "Vent", "Ensoleillement", "Précipitation"], "latitude": 24.564552, "longitude": 13.568783, "communication": "SATELLITE"}	{"nom": "station sahara sud", "status": "MAINTENANCE", "energie": "SOLAIRE", "capteurs": ["Température", "Pression", "Vent", "Ensoleillement", "Précipitation"], "latitude": 24.564552, "longitude": 13.568783, "communication": "SATELLITE"}	2026-02-07 15:13:27.133585+01	127.0.0.1	1	\N	da138147-fa03-4867-b261-5c0f82707801
cc2a530b-776c-4920-84d1-91809398d384	CREATE_STATION	Création de la station station sahara nord	\N	\N	2026-02-07 15:17:42.60841+01	127.0.0.1	1	\N	1a576c95-15ec-47b6-b6a4-46365dc97af5
0f08e7fd-e47e-470e-8761-04e1117e696f	UPDATE_STATION	Modification de la station station sahara nord	{"nom": "station sahara nord", "status": "EN_PANNE", "energie": "SOLAIRE", "capteurs": ["Température", "Pression", "Vent", "Ensoleillement", "Précipitation"], "latitude": 26.564552, "longitude": 14.568783, "communication": "SATELLITE"}	{"nom": "station sahara nord", "status": "ACTIF", "energie": "SOLAIRE", "capteurs": ["Température", "Pression", "Vent", "Ensoleillement", "Précipitation"], "latitude": 26.564547, "longitude": 14.568783, "communication": "SATELLITE"}	2026-02-08 11:56:16.848962+01	127.0.0.1	1	\N	1a576c95-15ec-47b6-b6a4-46365dc97af5
\.


--
-- TOC entry 5055 (class 0 OID 16516)
-- Dependencies: 235
-- Data for Name: users_station; Type: TABLE DATA; Schema: public; Owner: desertmet_user
--

COPY public.users_station (id, nom, latitude, longitude, energie, communication, status, capteur_temperature, capteur_pression, capteur_vent, capteur_ensoleillement, capteur_precipitation, date_creation, date_mise_a_jour) FROM stdin;
1a576c95-15ec-47b6-b6a4-46365dc97af5	station sahara nord	26.564547	14.568783	SOLAIRE	SATELLITE	ACTIF	t	t	t	t	t	2026-02-07 15:17:42.578216+01	2026-02-08 11:56:16.551071+01
da138147-fa03-4867-b261-5c0f82707801	station sahara sud	24.564552	13.568783	SOLAIRE	SATELLITE	ACTIF	t	t	t	t	t	2026-02-07 13:44:19.652625+01	2026-02-08 11:59:42.257941+01
\.


--
-- TOC entry 5050 (class 0 OID 16478)
-- Dependencies: 230
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: desertmet_user
--

COPY public.users_user (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, email, fullname, is_desert_admin, date_joined) FROM stdin;
7	pbkdf2_sha256$1200000$Hd2VaOCDUGvMmZZopMqxCY$3ZpzdmW/punVs7eEaMJ+ULXgf4bHl2uy0jFI2Onx/Ic=	\N	f			f	t	test@example.com	Test User	f	2026-02-06 23:16:09.045502+01
8	pbkdf2_sha256$1200000$vfKLLRVePqMJjIFFqUajOM$Wnb0w9/Yqel+kk2PSfgeCDzAUR+CwvNSy1dRdQMAj8s=	2026-02-07 14:48:03.843169+01	f			f	t	kpi150906@gmail.com	kpwanda yvan	f	2026-02-07 12:09:57.881545+01
1	pbkdf2_sha256$1200000$qiMe8kHVI8Gb9xgG35lyv7$e2hPjDNVuqt+FC7tzj7JMCQRuwtmSe4uKzEquxyseXY=	2026-02-07 15:12:25.197439+01	t			t	t	kpi150906@desertmet.com	jean othniel	t	2026-02-06 22:21:02.830498+01
\.


--
-- TOC entry 5052 (class 0 OID 16499)
-- Dependencies: 232
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: desertmet_user
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 5054 (class 0 OID 16508)
-- Dependencies: 234
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: desertmet_user
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5058 (class 0 OID 16549)
-- Dependencies: 238
-- Data for Name: users_weatherdata; Type: TABLE DATA; Schema: public; Owner: desertmet_user
--

COPY public.users_weatherdata (id, temperature, pression, vitesse_vent, precipitation, ensoleillement, "timestamp", date_reception, station_id) FROM stdin;
1	36.24	1007.24	27.40	0.00	742.25	2026-02-07 14:10:26.479685+01	2026-02-07 14:10:26.481036+01	da138147-fa03-4867-b261-5c0f82707801
2	31.74	1022.29	14.26	0.00	773.67	2026-02-07 14:10:40.529936+01	2026-02-07 14:10:40.531076+01	da138147-fa03-4867-b261-5c0f82707801
3	36.55	1012.02	9.72	0.00	680.16	2026-02-07 14:10:51.816199+01	2026-02-07 14:10:51.816568+01	da138147-fa03-4867-b261-5c0f82707801
4	41.33	1016.26	6.98	0.00	700.79	2026-02-07 14:11:10.806852+01	2026-02-07 14:11:10.80763+01	da138147-fa03-4867-b261-5c0f82707801
5	42.23	1022.39	17.28	0.00	676.30	2026-02-07 14:46:07.179546+01	2026-02-07 14:46:07.202822+01	da138147-fa03-4867-b261-5c0f82707801
6	30.43	1020.59	13.75	0.00	741.15	2026-02-07 14:46:25.975893+01	2026-02-07 14:46:25.976348+01	da138147-fa03-4867-b261-5c0f82707801
7	34.62	1011.94	11.60	0.00	736.45	2026-02-07 14:46:40.511782+01	2026-02-07 14:46:40.512666+01	da138147-fa03-4867-b261-5c0f82707801
8	38.46	1004.58	21.25	0.00	709.96	2026-02-07 14:46:59.435694+01	2026-02-07 14:46:59.436581+01	da138147-fa03-4867-b261-5c0f82707801
9	39.52	1008.80	12.95	0.00	799.18	2026-02-07 14:47:09.763685+01	2026-02-07 14:47:09.763972+01	da138147-fa03-4867-b261-5c0f82707801
10	30.58	1013.82	17.72	0.00	721.79	2026-02-07 14:47:23.465701+01	2026-02-07 14:47:23.466085+01	da138147-fa03-4867-b261-5c0f82707801
11	41.80	1010.44	31.66	0.00	780.15	2026-02-07 14:47:36.926673+01	2026-02-07 14:47:36.927518+01	da138147-fa03-4867-b261-5c0f82707801
12	31.27	1010.57	11.26	0.00	782.57	2026-02-07 14:47:51.542493+01	2026-02-07 14:47:51.543203+01	da138147-fa03-4867-b261-5c0f82707801
13	41.11	1016.61	6.61	0.00	759.96	2026-02-07 14:48:11.036504+01	2026-02-07 14:48:11.037598+01	da138147-fa03-4867-b261-5c0f82707801
14	28.39	1020.07	22.27	0.00	781.62	2026-02-07 14:48:26.095585+01	2026-02-07 14:48:26.096407+01	da138147-fa03-4867-b261-5c0f82707801
15	39.85	1008.53	21.22	0.00	783.82	2026-02-07 14:48:42.53975+01	2026-02-07 14:48:42.54006+01	da138147-fa03-4867-b261-5c0f82707801
16	38.36	1018.42	21.82	0.00	763.76	2026-02-07 14:49:00.267257+01	2026-02-07 14:49:00.268581+01	da138147-fa03-4867-b261-5c0f82707801
17	35.21	1003.37	13.97	0.00	802.77	2026-02-07 14:49:14.329423+01	2026-02-07 14:49:14.330255+01	da138147-fa03-4867-b261-5c0f82707801
18	29.38	1022.60	17.02	0.00	762.80	2026-02-07 14:49:28.711816+01	2026-02-07 14:49:28.712659+01	da138147-fa03-4867-b261-5c0f82707801
19	44.92	1019.46	24.78	0.00	693.67	2026-02-07 14:49:48.400506+01	2026-02-07 14:49:48.40138+01	da138147-fa03-4867-b261-5c0f82707801
20	38.55	1018.85	17.84	0.00	717.60	2026-02-07 14:50:06.996105+01	2026-02-07 14:50:06.996937+01	da138147-fa03-4867-b261-5c0f82707801
21	31.89	1006.84	22.66	0.00	729.21	2026-02-07 14:50:18.152035+01	2026-02-07 14:50:18.152338+01	da138147-fa03-4867-b261-5c0f82707801
22	42.22	1020.76	20.45	0.00	704.11	2026-02-07 14:50:31.935301+01	2026-02-07 14:50:31.936847+01	da138147-fa03-4867-b261-5c0f82707801
23	42.00	1018.26	27.61	0.00	728.01	2026-02-07 14:50:48.899632+01	2026-02-07 14:50:48.90047+01	da138147-fa03-4867-b261-5c0f82707801
24	41.57	1011.77	20.39	0.00	820.48	2026-02-07 14:51:05.04559+01	2026-02-07 14:51:05.046424+01	da138147-fa03-4867-b261-5c0f82707801
25	31.27	1010.66	28.29	0.00	704.78	2026-02-07 14:51:22.626601+01	2026-02-07 14:51:22.627407+01	da138147-fa03-4867-b261-5c0f82707801
26	41.32	1018.49	21.46	0.00	718.49	2026-02-07 14:51:38.645605+01	2026-02-07 14:51:38.646433+01	da138147-fa03-4867-b261-5c0f82707801
27	35.02	1005.94	21.69	0.00	669.26	2026-02-07 14:51:49.904426+01	2026-02-07 14:51:49.905259+01	da138147-fa03-4867-b261-5c0f82707801
28	34.43	1018.30	21.57	0.00	676.87	2026-02-07 14:52:04.365795+01	2026-02-07 14:52:04.366418+01	da138147-fa03-4867-b261-5c0f82707801
29	34.64	1005.76	23.89	0.00	703.61	2026-02-07 14:52:22.524668+01	2026-02-07 14:52:22.524972+01	da138147-fa03-4867-b261-5c0f82707801
30	28.70	1004.03	21.19	0.00	683.37	2026-02-07 14:52:38.401458+01	2026-02-07 14:52:38.402505+01	da138147-fa03-4867-b261-5c0f82707801
31	44.88	1016.97	13.02	0.00	764.80	2026-02-07 14:52:52.12834+01	2026-02-07 14:52:52.128798+01	da138147-fa03-4867-b261-5c0f82707801
32	45.45	1009.82	14.80	0.00	799.40	2026-02-07 14:53:06.773197+01	2026-02-07 14:53:06.773604+01	da138147-fa03-4867-b261-5c0f82707801
33	40.97	1013.12	20.48	0.00	798.31	2026-02-07 14:53:21.966201+01	2026-02-07 14:53:21.967131+01	da138147-fa03-4867-b261-5c0f82707801
34	44.00	1021.55	21.81	0.00	674.51	2026-02-07 14:53:37.960753+01	2026-02-07 14:53:37.961201+01	da138147-fa03-4867-b261-5c0f82707801
35	42.87	1011.55	32.80	1.82	795.74	2026-02-07 14:53:57.809599+01	2026-02-07 14:53:57.809871+01	da138147-fa03-4867-b261-5c0f82707801
36	44.92	1004.58	25.43	0.78	719.34	2026-02-07 14:54:16.128063+01	2026-02-07 14:54:16.128346+01	da138147-fa03-4867-b261-5c0f82707801
37	42.14	1006.18	20.31	0.00	806.00	2026-02-07 14:54:32.667174+01	2026-02-07 14:54:32.667442+01	da138147-fa03-4867-b261-5c0f82707801
38	41.27	1010.09	18.52	0.00	693.76	2026-02-07 14:54:44.86904+01	2026-02-07 14:54:44.869488+01	da138147-fa03-4867-b261-5c0f82707801
39	37.16	1022.99	26.17	0.00	752.59	2026-02-07 14:54:59.082344+01	2026-02-07 14:54:59.083251+01	da138147-fa03-4867-b261-5c0f82707801
40	42.07	1018.66	22.92	0.00	698.76	2026-02-07 14:55:15.743828+01	2026-02-07 14:55:15.744306+01	da138147-fa03-4867-b261-5c0f82707801
41	39.50	1020.29	9.10	0.00	768.32	2026-02-07 14:55:31.698733+01	2026-02-07 14:55:31.699638+01	da138147-fa03-4867-b261-5c0f82707801
42	34.91	1005.90	21.86	0.00	788.43	2026-02-07 14:55:48.81973+01	2026-02-07 14:55:48.820755+01	da138147-fa03-4867-b261-5c0f82707801
43	31.27	1003.69	14.88	0.00	706.37	2026-02-07 14:56:06.576757+01	2026-02-07 14:56:06.577588+01	da138147-fa03-4867-b261-5c0f82707801
44	31.24	1010.05	12.23	0.00	803.17	2026-02-07 14:56:19.776794+01	2026-02-07 14:56:19.777271+01	da138147-fa03-4867-b261-5c0f82707801
45	29.32	1007.54	18.01	0.00	779.70	2026-02-07 14:56:37.907663+01	2026-02-07 14:56:37.90891+01	da138147-fa03-4867-b261-5c0f82707801
46	35.38	1017.82	27.43	0.00	764.93	2026-02-07 14:56:49.662634+01	2026-02-07 14:56:49.66344+01	da138147-fa03-4867-b261-5c0f82707801
47	33.26	1014.32	16.05	0.00	675.49	2026-02-07 14:57:06.738593+01	2026-02-07 14:57:06.739431+01	da138147-fa03-4867-b261-5c0f82707801
48	39.25	1019.54	16.01	0.00	745.60	2026-02-07 14:57:21.60414+01	2026-02-07 14:57:21.605128+01	da138147-fa03-4867-b261-5c0f82707801
49	35.37	1022.48	19.15	0.00	734.30	2026-02-07 14:57:39.898558+01	2026-02-07 14:57:39.898832+01	da138147-fa03-4867-b261-5c0f82707801
50	42.72	1004.64	14.59	0.00	763.13	2026-02-07 14:57:52.801779+01	2026-02-07 14:57:52.802593+01	da138147-fa03-4867-b261-5c0f82707801
51	33.99	1014.60	25.88	0.00	714.15	2026-02-07 14:58:11.149733+01	2026-02-07 14:58:11.150586+01	da138147-fa03-4867-b261-5c0f82707801
52	38.55	1018.27	24.26	0.00	830.82	2026-02-07 14:58:22.003325+01	2026-02-07 14:58:22.004126+01	da138147-fa03-4867-b261-5c0f82707801
53	30.38	1022.19	14.44	0.00	777.57	2026-02-07 14:58:35.378559+01	2026-02-07 14:58:35.379471+01	da138147-fa03-4867-b261-5c0f82707801
54	37.88	1003.37	19.40	0.00	761.22	2026-02-07 14:58:51.068101+01	2026-02-07 14:58:51.068922+01	da138147-fa03-4867-b261-5c0f82707801
55	35.07	1019.60	16.78	0.00	778.40	2026-02-07 14:59:07.917386+01	2026-02-07 14:59:07.918197+01	da138147-fa03-4867-b261-5c0f82707801
56	40.37	1007.94	6.67	0.00	772.00	2026-02-07 14:59:27.915649+01	2026-02-07 14:59:27.916485+01	da138147-fa03-4867-b261-5c0f82707801
57	32.50	1012.47	10.15	0.00	750.59	2026-02-07 14:59:40.186544+01	2026-02-07 14:59:40.187446+01	da138147-fa03-4867-b261-5c0f82707801
58	30.63	1014.71	27.26	0.00	743.82	2026-02-07 14:59:54.629939+01	2026-02-07 14:59:54.630915+01	da138147-fa03-4867-b261-5c0f82707801
59	42.48	1010.50	15.36	0.00	645.36	2026-02-07 15:00:11.331038+01	2026-02-07 15:00:11.331391+01	da138147-fa03-4867-b261-5c0f82707801
60	31.65	1004.92	19.70	0.00	644.89	2026-02-07 15:00:23.949329+01	2026-02-07 15:00:23.950127+01	da138147-fa03-4867-b261-5c0f82707801
61	35.24	1006.27	30.45	0.00	587.89	2026-02-07 15:00:41.710162+01	2026-02-07 15:00:41.710587+01	da138147-fa03-4867-b261-5c0f82707801
62	32.50	1003.88	25.94	0.00	564.00	2026-02-07 15:00:54.864947+01	2026-02-07 15:00:54.865294+01	da138147-fa03-4867-b261-5c0f82707801
63	31.98	1019.58	19.60	0.00	621.99	2026-02-07 15:01:08.647923+01	2026-02-07 15:01:08.648749+01	da138147-fa03-4867-b261-5c0f82707801
64	33.71	1014.74	18.36	0.00	593.58	2026-02-07 15:01:21.399436+01	2026-02-07 15:01:21.399867+01	da138147-fa03-4867-b261-5c0f82707801
65	34.91	1019.24	24.28	0.00	643.76	2026-02-07 15:01:37.497989+01	2026-02-07 15:01:37.498395+01	da138147-fa03-4867-b261-5c0f82707801
66	39.49	1017.66	19.14	0.00	657.65	2026-02-07 15:01:54.251866+01	2026-02-07 15:01:54.252153+01	da138147-fa03-4867-b261-5c0f82707801
67	39.44	1010.68	20.22	0.00	544.97	2026-02-07 15:02:11.469604+01	2026-02-07 15:02:11.470033+01	da138147-fa03-4867-b261-5c0f82707801
68	38.65	1011.38	21.70	0.00	641.32	2026-02-07 15:02:25.078699+01	2026-02-07 15:02:25.07925+01	da138147-fa03-4867-b261-5c0f82707801
69	41.14	1009.43	11.63	0.00	655.56	2026-02-07 15:02:45.032374+01	2026-02-07 15:02:45.032735+01	da138147-fa03-4867-b261-5c0f82707801
70	41.66	1003.90	15.93	0.00	625.75	2026-02-07 15:03:00.477318+01	2026-02-07 15:03:00.477787+01	da138147-fa03-4867-b261-5c0f82707801
71	36.07	1005.92	17.86	1.75	631.11	2026-02-07 15:03:16.843318+01	2026-02-07 15:03:16.843824+01	da138147-fa03-4867-b261-5c0f82707801
72	33.14	1007.73	21.43	0.00	647.01	2026-02-07 15:03:36.824848+01	2026-02-07 15:03:36.825653+01	da138147-fa03-4867-b261-5c0f82707801
73	37.99	1018.02	23.66	0.00	611.47	2026-02-07 15:03:55.231424+01	2026-02-07 15:03:55.232221+01	da138147-fa03-4867-b261-5c0f82707801
74	32.22	1022.66	10.93	0.00	600.22	2026-02-07 15:04:09.072168+01	2026-02-07 15:04:09.07296+01	da138147-fa03-4867-b261-5c0f82707801
75	30.87	1010.86	21.34	0.00	580.51	2026-02-07 15:04:28.507492+01	2026-02-07 15:04:28.507855+01	da138147-fa03-4867-b261-5c0f82707801
76	44.19	1021.61	12.81	0.00	597.89	2026-02-07 15:04:38.67243+01	2026-02-07 15:04:38.673243+01	da138147-fa03-4867-b261-5c0f82707801
77	32.42	1011.03	22.52	0.00	610.07	2026-02-07 15:04:50.965028+01	2026-02-07 15:04:50.965337+01	da138147-fa03-4867-b261-5c0f82707801
78	30.67	1003.65	20.08	0.00	571.49	2026-02-07 15:05:06.959877+01	2026-02-07 15:05:06.960895+01	da138147-fa03-4867-b261-5c0f82707801
79	42.16	1016.35	9.92	0.00	593.01	2026-02-07 15:05:22.891459+01	2026-02-07 15:05:22.891772+01	da138147-fa03-4867-b261-5c0f82707801
80	30.53	1008.57	22.33	0.00	626.73	2026-02-07 15:05:37.628069+01	2026-02-07 15:05:37.628861+01	da138147-fa03-4867-b261-5c0f82707801
81	33.47	1014.24	23.06	0.00	648.40	2026-02-07 15:05:48.779951+01	2026-02-07 15:05:48.780747+01	da138147-fa03-4867-b261-5c0f82707801
82	45.95	1022.92	25.91	0.00	645.73	2026-02-07 15:06:07.404094+01	2026-02-07 15:06:07.404852+01	da138147-fa03-4867-b261-5c0f82707801
83	31.04	1012.78	20.18	0.00	566.58	2026-02-07 15:06:26.022641+01	2026-02-07 15:06:26.022972+01	da138147-fa03-4867-b261-5c0f82707801
84	32.17	1016.84	14.83	0.00	636.21	2026-02-07 15:06:45.402393+01	2026-02-07 15:06:45.403126+01	da138147-fa03-4867-b261-5c0f82707801
85	40.85	1017.27	11.82	0.00	661.18	2026-02-07 15:06:59.141169+01	2026-02-07 15:06:59.141542+01	da138147-fa03-4867-b261-5c0f82707801
86	41.51	1008.36	24.10	0.00	654.05	2026-02-07 15:07:17.822714+01	2026-02-07 15:07:17.823499+01	da138147-fa03-4867-b261-5c0f82707801
87	28.92	1016.26	27.04	0.00	619.39	2026-02-07 15:17:52.270219+01	2026-02-07 15:17:52.271158+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
88	30.98	1022.81	5.69	0.28	623.06	2026-02-07 15:18:07.55739+01	2026-02-07 15:18:07.558229+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
89	35.48	1017.04	27.25	0.00	647.17	2026-02-07 15:18:25.277978+01	2026-02-07 15:18:25.279696+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
90	33.81	1011.39	16.27	0.00	625.40	2026-02-07 15:18:45.172364+01	2026-02-07 15:18:45.172816+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
91	42.23	1007.98	18.44	0.00	574.48	2026-02-07 15:19:01.362229+01	2026-02-07 15:19:01.362512+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
92	42.43	1009.92	21.72	0.00	589.80	2026-02-07 15:19:14.470704+01	2026-02-07 15:19:14.47099+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
93	32.80	1005.94	21.49	0.00	616.69	2026-02-08 11:56:29.475887+01	2026-02-08 11:56:29.491302+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
94	33.62	1018.20	25.93	0.00	660.63	2026-02-08 11:56:44.84988+01	2026-02-08 11:56:44.850432+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
95	31.83	1004.92	30.89	0.00	622.20	2026-02-08 11:57:02.705716+01	2026-02-08 11:57:02.706454+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
96	30.72	1003.71	21.40	0.00	655.47	2026-02-08 11:57:20.705569+01	2026-02-08 11:57:20.706108+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
97	35.43	1008.14	16.65	0.00	601.14	2026-02-08 11:57:33.21563+01	2026-02-08 11:57:33.216097+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
98	33.24	1011.64	23.07	0.00	592.72	2026-02-08 11:57:49.77812+01	2026-02-08 11:57:49.77899+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
99	37.30	1012.84	16.06	0.00	615.32	2026-02-08 11:58:00.272189+01	2026-02-08 11:58:00.272549+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
100	37.97	1012.60	17.99	0.00	627.00	2026-02-08 11:58:19.899894+01	2026-02-08 11:58:19.900477+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
101	41.07	1011.26	15.89	0.00	628.61	2026-02-08 11:58:39.392349+01	2026-02-08 11:58:39.392674+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
102	44.62	1021.75	24.74	0.00	662.98	2026-02-08 11:58:52.108864+01	2026-02-08 11:58:52.109489+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
103	42.44	1017.86	17.93	0.00	565.60	2026-02-08 11:59:12.504995+01	2026-02-08 11:59:12.50899+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
104	36.37	1018.56	26.48	0.00	597.71	2026-02-08 11:59:22.597328+01	2026-02-08 11:59:22.597894+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
105	29.16	1020.84	22.04	0.00	585.74	2026-02-08 11:59:42.253642+01	2026-02-08 11:59:42.254263+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
106	40.27	1011.87	19.36	0.00	800.64	2026-02-08 12:00:01.620357+01	2026-02-08 12:00:01.620945+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
107	34.84	1008.84	15.97	0.00	724.48	2026-02-08 12:00:01.625483+01	2026-02-08 12:00:01.626061+01	da138147-fa03-4867-b261-5c0f82707801
108	36.02	1009.06	17.25	0.00	765.66	2026-02-08 12:00:14.780549+01	2026-02-08 12:00:14.781017+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
109	39.33	1018.17	21.75	0.00	763.47	2026-02-08 12:00:14.7823+01	2026-02-08 12:00:14.782758+01	da138147-fa03-4867-b261-5c0f82707801
110	42.73	1008.85	26.85	1.54	830.75	2026-02-08 12:00:26.955283+01	2026-02-08 12:00:26.955596+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
111	43.67	1016.00	11.87	0.00	812.18	2026-02-08 12:00:27.659463+01	2026-02-08 12:00:27.659758+01	da138147-fa03-4867-b261-5c0f82707801
112	36.56	1016.43	9.39	0.00	698.09	2026-02-08 12:00:43.265395+01	2026-02-08 12:00:43.265901+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
113	35.72	1016.57	21.38	0.00	764.71	2026-02-08 12:00:43.267354+01	2026-02-08 12:00:43.267855+01	da138147-fa03-4867-b261-5c0f82707801
114	38.91	1017.27	18.10	0.00	701.24	2026-02-08 12:00:58.327977+01	2026-02-08 12:00:58.328521+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
115	33.08	1010.32	20.23	0.00	729.45	2026-02-08 12:00:58.32984+01	2026-02-08 12:00:58.330362+01	da138147-fa03-4867-b261-5c0f82707801
116	41.61	1018.58	23.87	0.00	758.71	2026-02-08 12:01:10.836223+01	2026-02-08 12:01:10.836786+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
117	40.77	1007.03	13.18	0.00	773.94	2026-02-08 12:01:11.831109+01	2026-02-08 12:01:11.832197+01	da138147-fa03-4867-b261-5c0f82707801
118	43.23	1009.50	14.06	0.00	744.45	2026-02-08 12:01:28.47063+01	2026-02-08 12:01:28.471177+01	1a576c95-15ec-47b6-b6a4-46365dc97af5
119	34.58	1014.98	24.23	0.00	698.63	2026-02-08 12:01:28.472454+01	2026-02-08 12:01:28.472914+01	da138147-fa03-4867-b261-5c0f82707801
\.


--
-- TOC entry 5067 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: desertmet_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5068 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: desertmet_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5069 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: desertmet_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 36, true);


--
-- TOC entry 5070 (class 0 OID 0)
-- Dependencies: 239
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: desertmet_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 5071 (class 0 OID 0)
-- Dependencies: 221
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: desertmet_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 9, true);


--
-- TOC entry 5072 (class 0 OID 0)
-- Dependencies: 219
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: desertmet_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- TOC entry 5073 (class 0 OID 0)
-- Dependencies: 231
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: desertmet_user
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- TOC entry 5074 (class 0 OID 0)
-- Dependencies: 229
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: desertmet_user
--

SELECT pg_catalog.setval('public.users_user_id_seq', 8, true);


--
-- TOC entry 5075 (class 0 OID 0)
-- Dependencies: 233
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: desertmet_user
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5076 (class 0 OID 0)
-- Dependencies: 237
-- Name: users_weatherdata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: desertmet_user
--

SELECT pg_catalog.setval('public.users_weatherdata_id_seq', 119, true);


--
-- TOC entry 4826 (class 2606 OID 16474)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4831 (class 2606 OID 16459)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4834 (class 2606 OID 16448)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4828 (class 2606 OID 16437)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4821 (class 2606 OID 16450)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4823 (class 2606 OID 16429)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4873 (class 2606 OID 16632)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4816 (class 2606 OID 16419)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4818 (class 2606 OID 16417)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4814 (class 2606 OID 16407)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4877 (class 2606 OID 16654)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4863 (class 2606 OID 16547)
-- Name: users_adminlog users_adminlog_pkey; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_adminlog
    ADD CONSTRAINT users_adminlog_pkey PRIMARY KEY (id);


--
-- TOC entry 4856 (class 2606 OID 16536)
-- Name: users_station users_station_nom_key; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_station
    ADD CONSTRAINT users_station_nom_key UNIQUE (nom);


--
-- TOC entry 4858 (class 2606 OID 16534)
-- Name: users_station users_station_pkey; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_station
    ADD CONSTRAINT users_station_pkey PRIMARY KEY (id);


--
-- TOC entry 4837 (class 2606 OID 16497)
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- TOC entry 4842 (class 2606 OID 16506)
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4845 (class 2606 OID 16560)
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4839 (class 2606 OID 16495)
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4848 (class 2606 OID 16515)
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4851 (class 2606 OID 16574)
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4869 (class 2606 OID 16557)
-- Name: users_weatherdata users_weatherdata_pkey; Type: CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_weatherdata
    ADD CONSTRAINT users_weatherdata_pkey PRIMARY KEY (id);


--
-- TOC entry 4824 (class 1259 OID 16475)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4829 (class 1259 OID 16470)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4832 (class 1259 OID 16471)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4819 (class 1259 OID 16456)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4871 (class 1259 OID 16643)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4874 (class 1259 OID 16644)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4875 (class 1259 OID 16656)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4878 (class 1259 OID 16655)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4859 (class 1259 OID 16609)
-- Name: users_admin_action__349571_idx; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_admin_action__349571_idx ON public.users_adminlog USING btree (action_type);


--
-- TOC entry 4860 (class 1259 OID 16608)
-- Name: users_admin_admin_i_cce586_idx; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_admin_admin_i_cce586_idx ON public.users_adminlog USING btree (admin_id, "timestamp");


--
-- TOC entry 4861 (class 1259 OID 16605)
-- Name: users_adminlog_admin_id_bee55366; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_adminlog_admin_id_bee55366 ON public.users_adminlog USING btree (admin_id);


--
-- TOC entry 4864 (class 1259 OID 16607)
-- Name: users_adminlog_station_concerne_id_236283f5; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_adminlog_station_concerne_id_236283f5 ON public.users_adminlog USING btree (station_concerne_id);


--
-- TOC entry 4865 (class 1259 OID 16606)
-- Name: users_adminlog_utilisateur_concerne_id_71b392aa; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_adminlog_utilisateur_concerne_id_71b392aa ON public.users_adminlog USING btree (utilisateur_concerne_id);


--
-- TOC entry 4852 (class 1259 OID 16589)
-- Name: users_stati_latitud_1d83be_idx; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_stati_latitud_1d83be_idx ON public.users_station USING btree (latitude, longitude);


--
-- TOC entry 4853 (class 1259 OID 16588)
-- Name: users_stati_status_5a997a_idx; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_stati_status_5a997a_idx ON public.users_station USING btree (status);


--
-- TOC entry 4854 (class 1259 OID 16587)
-- Name: users_station_nom_bb9cdd1c_like; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_station_nom_bb9cdd1c_like ON public.users_station USING btree (nom varchar_pattern_ops);


--
-- TOC entry 4835 (class 1259 OID 16558)
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- TOC entry 4840 (class 1259 OID 16572)
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- TOC entry 4843 (class 1259 OID 16571)
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- TOC entry 4846 (class 1259 OID 16586)
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4849 (class 1259 OID 16585)
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- TOC entry 4866 (class 1259 OID 16616)
-- Name: users_weath_station_26e0f6_idx; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_weath_station_26e0f6_idx ON public.users_weatherdata USING btree (station_id, "timestamp");


--
-- TOC entry 4867 (class 1259 OID 16617)
-- Name: users_weath_timesta_991d0e_idx; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_weath_timesta_991d0e_idx ON public.users_weatherdata USING btree ("timestamp");


--
-- TOC entry 4870 (class 1259 OID 16615)
-- Name: users_weatherdata_station_id_faee4466; Type: INDEX; Schema: public; Owner: desertmet_user
--

CREATE INDEX users_weatherdata_station_id_faee4466 ON public.users_weatherdata USING btree (station_id);


--
-- TOC entry 4880 (class 2606 OID 16465)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4881 (class 2606 OID 16460)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4879 (class 2606 OID 16451)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4890 (class 2606 OID 16633)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4891 (class 2606 OID 16638)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4886 (class 2606 OID 16590)
-- Name: users_adminlog users_adminlog_admin_id_bee55366_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_adminlog
    ADD CONSTRAINT users_adminlog_admin_id_bee55366_fk_users_user_id FOREIGN KEY (admin_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4887 (class 2606 OID 16600)
-- Name: users_adminlog users_adminlog_station_concerne_id_236283f5_fk_users_station_id; Type: FK CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_adminlog
    ADD CONSTRAINT users_adminlog_station_concerne_id_236283f5_fk_users_station_id FOREIGN KEY (station_concerne_id) REFERENCES public.users_station(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4888 (class 2606 OID 16595)
-- Name: users_adminlog users_adminlog_utilisateur_concerne_71b392aa_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_adminlog
    ADD CONSTRAINT users_adminlog_utilisateur_concerne_71b392aa_fk_users_use FOREIGN KEY (utilisateur_concerne_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4882 (class 2606 OID 16566)
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4883 (class 2606 OID 16561)
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4884 (class 2606 OID 16580)
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4885 (class 2606 OID 16575)
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4889 (class 2606 OID 16610)
-- Name: users_weatherdata users_weatherdata_station_id_faee4466_fk_users_station_id; Type: FK CONSTRAINT; Schema: public; Owner: desertmet_user
--

ALTER TABLE ONLY public.users_weatherdata
    ADD CONSTRAINT users_weatherdata_station_id_faee4466_fk_users_station_id FOREIGN KEY (station_id) REFERENCES public.users_station(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-02-08 14:01:58

--
-- PostgreSQL database dump complete
--

\unrestrict DbomEvbIBEXvAW50biw3SkaG8O3Ok0X92UGcy3Uj9VpNNcww8TiLlP6qDnthqXf

